PAGE_ACCESS_TOKEN = "EAAb6bzYnwgQBAJZBM4RCaAZBIRn9Koqhr1DbBsUf5GhdMuxbTOBnl3xZBwfqgnmMi4kgMZBhUkHJu8vnIlLmoJvY0FFoPhw1QakazEzhtyVWIG56VSZAwlML6cGSaiSlcvGePQn80YrJLsrVRZCmGbSIbuP1qJA3r49X7ZCByZBWqiV4i1X3EZAAV"

DEFAULT_IMG = "http://www.orangefairs.com/images/resource/event-manegment.jpg"